default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 10000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql
  user: <%= Rails.application.credentials.dig(:postgres, :user) %>
  password: <%= Rails.application.credentials.dig(:postgres, :password) %>
  database: <%= Rails.application.credentials.dig(:postgres, :database) %>
  